# Generated by Django 2.2.2 on 2019-06-16 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PokeData', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemgameindice',
            old_name='gmaeIndex',
            new_name='gameIndex',
        ),
        migrations.AlterField(
            model_name='move',
            name='targetId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PokeData.MoveTarget'),
        ),
    ]
