# Generated by Django 2.2.2 on 2019-06-16 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PokeData', '0002_auto_20190616_1316'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TypeGameIndices',
            new_name='TypeGameIndice',
        ),
        migrations.RenameField(
            model_name='pokemonevolution',
            old_name='realtivePhysicalStat',
            new_name='relativePhysicalStat',
        ),
        migrations.RenameField(
            model_name='pokemonitem',
            old_name='tarity',
            new_name='rarity',
        ),
    ]
